# Generated by Django 6.0.3 on 2026-03-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_end',
            field=models.DateTimeField(blank=True, help_text="The date and time when the user's subscription expires", null=True),
        ),
    ]
