# Generated by Django 6.0.3 on 2026-04-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blog_slug_alter_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='plan_expiry',
            new_name='subscription_expiry',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='paystack_ref',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='plan',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
