# Generated by Django 6.0.3 on 2026-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_is_paid_user_plan_alter_user_subscription_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
