# Generated by Django 6.0.3 on 2026-04-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_plan_expiry_profile_subscription_expiry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subscription_expiry',
            new_name='plan_expiry',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_paid',
        ),
    ]
