# Generated by Django 6.0.3 on 2026-04-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_subscription_expiry_profile_plan_expiry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='plan_expiry',
            new_name='subscription_expiry',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
