# Generated by Django 6.0.3 on 2026-03-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
