# Generated by Django 6.0.3 on 2026-03-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_trial_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='trial_end',
            new_name='trial_start',
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business')], default='free_trial', max_length=20),
        ),
    ]
