# Generated by Django 6.0.3 on 2026-04-07 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_plan_expiry_profile_subscription_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.business'),
        ),
    ]
