# Generated by Django 6.0.3 on 2026-04-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demovideo',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='demovideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='demovideo',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
