# Generated by Django 6.0.3 on 2026-04-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_uploaded_at_demovideo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demovideo',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
