# Generated by Django 6.0.3 on 2026-04-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_demovideo_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demovideo',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='demovideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='demo_videos/'),
        ),
    ]
